version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
  db:
    image: mysql:8.0.30
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: zxcv
      MYSQL_DATABASE: my_db
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: bestuser